version: "3"
services:
  mysql_container: # 해당 이름으로 찾아간다.
    image: mysql:latest
    container_name: mysql-local
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: board
      MYSQL_ROOT_PASSWORD: root123
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/folders/mysql # 다렉토리 마운트 설정
    restart: always

  redis_container:
    image: redis:latest
    container_name: redis_local
    ports:
      - 6380:6379
    volumes:
      - /var/folders/redis
    labels:
      - "name=redis"
      - "mode=standalone"
    # 컨테이너 종료시 재시작 여부 설정
    restart: always
    command: redis-server /var/folders/redis # volume 과 파일경로를 동일하게 해야한다.
#
#  board:
#    build: .
#    ports:
#      - 8080:8080
#    depends_on:
#      - mysql_container
#      - redis_container
#    environment:
#      DATABASE_URL: mysql_container
#      DATABASE_PORT: 3306
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root123
#      REDIS_URL : redis_container
#      REDIS_PORT: 6379
#
#volumes:
#  mysql_data:
#    driver: local